'use client'

import { useState } from 'react'
import { ExternalLink } from 'lucide-react'
import { formatDistanceToNow } from 'date-fns'
import { createClient } from '@/lib/supabase/client'
import { UrgencyBadge } from './urgency-badge'
import { cn } from '@/lib/utils'
import type { Update } from '@/types'

interface UpdateCardProps {
  update: Update
  isRead: boolean
  userId: string
}

export function UpdateCard({ update, isRead: initialRead, userId }: UpdateCardProps) {
  const [isRead, setIsRead] = useState(initialRead)

  const handleMarkRead = async () => {
    if (isRead) return
    setIsRead(true)
    const supabase = createClient()
    await supabase
      .from('user_update_reads')
      .insert({ user_id: userId, update_id: update.id })
      .then(() => {}) // fire-and-forget — optimistic update already applied
  }

  const sourceLabel = update.source
    ? `${update.source.name} · ${update.source.jurisdiction}`
    : update.jurisdiction

  return (
    <div
      onClick={handleMarkRead}
      className={cn(
        'group relative flex flex-col gap-3 rounded-xl border p-5 transition-colors cursor-pointer',
        isRead
          ? 'border-slate-800 bg-slate-900/40 hover:bg-slate-900/70'
          : 'border-slate-700 bg-slate-900 hover:bg-slate-800/60'
      )}
    >
      {/* Unread dot */}
      {!isRead && (
        <span className="absolute top-4 right-4 h-2 w-2 rounded-full bg-blue-500" />
      )}

      {/* Header row */}
      <div className="flex flex-wrap items-center gap-2 pr-4">
        <UrgencyBadge level={update.urgency_level} />
        {update.deadline_date && (
          <span className="rounded-full border border-amber-500/30 bg-amber-500/10 px-2.5 py-0.5 text-xs font-medium text-amber-400">
            Due {new Date(update.deadline_date).toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' })}
          </span>
        )}
      </div>

      {/* Title */}
      <h3 className={cn('font-semibold leading-snug', isRead ? 'text-slate-300' : 'text-white')}>
        {update.title}
      </h3>

      {/* Source */}
      <p className="text-xs text-slate-500">{sourceLabel}</p>

      {/* Summary */}
      <p className="text-sm text-slate-400 leading-relaxed line-clamp-2">{update.summary}</p>

      {/* Action items */}
      {update.action_items.length > 0 && (
        <ul className="space-y-1">
          {update.action_items.slice(0, 2).map((item, i) => (
            <li key={i} className="flex items-start gap-2 text-xs text-slate-500">
              <span className="mt-0.5 text-blue-500">·</span>
              {item}
            </li>
          ))}
        </ul>
      )}

      {/* Footer row */}
      <div className="flex items-center justify-between pt-1 border-t border-slate-800/60">
        <span className="text-xs text-slate-600">
          {formatDistanceToNow(new Date(update.created_at), { addSuffix: true })}
        </span>
        <a
          href={update.source_url}
          target="_blank"
          rel="noopener noreferrer"
          onClick={(e) => e.stopPropagation()}
          className="flex items-center gap-1.5 text-xs text-blue-500 hover:text-blue-400 transition-colors"
        >
          View official source
          <ExternalLink size={12} />
        </a>
      </div>

      {/* Per-card disclaimer */}
      <p className="text-[10px] text-slate-700 leading-relaxed">
        Summary generated by AI for informational purposes only. Verify directly with the official source before taking action.
      </p>
    </div>
  )
}
